name: AudioVGen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - conda-forge::ffmpeg #may have a dependency error on installation
  - tqdm
  - transformers
  - av 
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - huggingface_hub
    - descript-audio-codec
    - torch>=2.6.0
    - torchvision>=0.21.0
    - torchaudio>=2.6.0
    - wav2clip==0.1.0
    - resampy
    - soundfile
    - wandb==0.23.1
    - torchinfo
