name: AudioVGen
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - conda-forge::ffmpeg #may have a dependency error on installation
  - tqdm
  - pip
  - pip:
    - huggingface_hub
    - descript-audio-codec
